openapi: 3.0.0
info:
  title: GoGretzky API
  description: "Go Gretzky is committed to offering you an outstanding range of world class hockey products"
  version: 1.0.0
servers:
  - url: https://api.example.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /user/email:
    get:
      summary: Get the email of the logged in user
      responses:
        '200':
          description: Email of the logged in user
          content:
            application/json:
              schema:
                type: string
                example: "user@example.com"
  /user/address:
    get:
      summary: Get the home address of the logged in user
      responses:
        '200':
          description: Home address of the logged in user
          content:
            application/json:
              schema:
                type: object
                properties:
                  street:
                    type: string
                    example: "Main St"
                  number:
                    type: integer
                    example: "123"
                  city:
                    type: string
                    example: "Anytown"
                  state:
                    type: string
                    example: "CA"
                  zip:
                    type: string
                    example: "12345"
                  country:
                    type: string
                    example: "USA"
    post:
      summary: Add a home address to the logged in user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                street:
                  type: string
                  example: "Main St"
                number:
                  type: integer
                  example: "123"
                city:
                  type: string
                  example: "Anytown"
                state:
                  type: string
                  example: "CA"
                zip:
                  type: string
                  example: "12345"
                country:
                  type: string
                  example: "USA"
      responses:
        '200':
          description: Successfully added home address to the logged in user
  /user/subscription:
    get:
      summary: Get the subscription of the logged in user
      responses:
        '200':
          description: Subscription of the logged in user
          content:
            application/json:
              schema:
                type: object
                properties:
                  from:
                    type: string
                    format: date-time
                    example: "2022-01-01T00:00:00Z"
                  to:
                    type: string
                    format: date-time
                    example: "2022-12-31T23:59:59Z"
                  sku:
                    type: array
                    items:
                      type: string
                      example: "SKU22005"
                  child:
                    type: string
                    format: uuid
                    example: "123e4567-e89b-12d3-a456-426655440000"
    post:
      summary: Add a subscription to the logged in user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                  format: date-time
                  example: "2022-01-01T00:00:00Z"
                to:
                  type: string
                  format: date-time
                  example: "2022-12-31T23:59:59Z"
                sku:
                  type: array
                  items:
                    type: string
                    example: "SKU22005"
                child:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426655440000"
      responses:
        '200':
          description: Successfully added subscription to the logged in user
  /user/child:
    post:
      summary: Add a child to the logged in user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                given_name:
                  type: string
                  example: "John"
                year_of_birth:
                  type: integer
                  format: int32
                  example: 2010
                gender:
                  type: string
                  example: "male"
                cloth_size:
                  type: integer
                  format: int32
                  example: 122
                shoe_size:
                  type: integer
                  format: int32
                  example: 36
                helmet_size:
                  type: integer
                  format: int32
                  example: 52
      responses:
        '200':
          description: Successfully added child to the logged in user
  /user/child/{childId}:
    get:
      summary: Get the child by id
      parameters:
        - name: childId
          in: path
          description: Id of the child to get
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Child information
          content:
            application/json:
              schema:
                type: object
                properties:
                  given_name:
                    type: string
                    example: "John"
                  year_of_birth:
                    type: integer
                    format: int32
                    example: 2010
                  gender:
                    type: string
                    example: "male"
                  cloth_size:
                    type: integer
                    format: int32
                    example: 122
                  shoe_size:
                    type: integer
                    format: int32
                    example: 36
                  helmet_size:
                    type: integer
                    format: int32
                    example: 52
