openapi: 3.0.0
info:
  title: GoGretzky API
  description: Go Gretzky is committed to offering you an outstanding range of world
    class hockey products
  version: 1.0.0
servers:
  - url: https://api.example.com
security:
  - bearerAuth: []
paths:
  /user/email:
    get:
      summary: Get the email of the logged in user
      operationId: user_email_get
      responses:
        "200":
          description: Email of the logged in user
          content:
            application/json:
              schema:
                type: string
                example: user@example.com
                x-content-type: application/json
      x-openapi-router-controller: go_gretzky.controllers.default_controller
  /user/address:
    get:
      summary: Get the home address of the logged in user
      operationId: user_address_get
      responses:
        "200":
          description: Home address of the logged in user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-openapi-router-controller: go_gretzky.controllers.default_controller
    post:
      summary: Add a home address to the logged in user
      operationId: user_address_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_address_body'
      responses:
        "200":
          description: Successfully added home address to the logged in user
      x-openapi-router-controller: go_gretzky.controllers.default_controller
  /user/subscription:
    get:
      summary: Get the subscription of the logged in user
      operationId: user_subscription_get
      responses:
        "200":
          description: Subscription of the logged in user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
      x-openapi-router-controller: go_gretzky.controllers.default_controller
    post:
      summary: Add a subscription to the logged in user
      operationId: user_subscription_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_subscription_body'
      responses:
        "200":
          description: Successfully added subscription to the logged in user
      x-openapi-router-controller: go_gretzky.controllers.default_controller
  /user/child:
    post:
      summary: Add a child to the logged in user
      operationId: user_child_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_child_body'
      responses:
        "200":
          description: Successfully added child to the logged in user
      x-openapi-router-controller: go_gretzky.controllers.default_controller
  /user/child/{childId}:
    get:
      summary: Get the child by id
      operationId: user_child_child_id_get
      parameters:
        - name: childId
          in: path
          description: Id of the child to get
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Child information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_child_body'
      x-openapi-router-controller: go_gretzky.controllers.default_controller
components:
  schemas:
    user_address_body:
      type: object
      properties:
        street:
          type: string
          example: Main St
        number:
          type: integer
          example: 123
        city:
          type: string
          example: Anytown
        state:
          type: string
          example: CA
        zip:
          type: string
          example: "12345"
        country:
          type: string
          example: USA
    inline_response_200_1:
      type: object
      properties:
        from:
          type: string
          format: date-time
          example: 2022-01-01T00:00:00Z
        to:
          type: string
          format: date-time
          example: 2022-12-31T23:59:59Z
        sku:
          type: array
          items:
            type: string
            example: SKU22005
        child:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426655440000
      example:
        from: 2022-01-01T00:00:00Z
        to: 2022-12-31T23:59:59Z
        sku:
          - SKU22005
          - SKU22005
        child: 123e4567-e89b-12d3-a456-426655440000
    inline_response_200:
      type: object
      properties:
        street:
          type: string
          example: Main St
        number:
          type: integer
          example: 123
        city:
          type: string
          example: Anytown
        state:
          type: string
          example: CA
        zip:
          type: string
          example: "12345"
        country:
          type: string
          example: USA
      example:
        zip: "12345"
        number: 123
        country: USA
        city: Anytown
        street: Main St
        state: CA
    user_child_body:
      type: object
      properties:
        given_name:
          type: string
          example: John
        year_of_birth:
          type: integer
          format: int32
          example: 2010
        gender:
          type: string
          example: male
        cloth_size:
          type: integer
          format: int32
          example: 122
        shoe_size:
          type: integer
          format: int32
          example: 36
        helmet_size:
          type: integer
          format: int32
          example: 52
      example:
        shoe_size: 36
        gender: male
        cloth_size: 122
        helmet_size: 52
        given_name: John
        year_of_birth: 2010
    user_subscription_body:
      type: object
      properties:
        from:
          type: string
          format: date-time
          example: 2022-01-01T00:00:00Z
        to:
          type: string
          format: date-time
          example: 2022-12-31T23:59:59Z
        sku:
          type: array
          items:
            type: string
            example: SKU22005
        child:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426655440000
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: go_gretzky.controllers.authorization_controller.check_bearerAuth
