# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _from=None, to=None, sku=None, child=None):  # noqa: E501
        """InlineResponse2001 - a model defined in OpenAPI

        :param _from: The _from of this InlineResponse2001.  # noqa: E501
        :type _from: datetime
        :param to: The to of this InlineResponse2001.  # noqa: E501
        :type to: datetime
        :param sku: The sku of this InlineResponse2001.  # noqa: E501
        :type sku: List[str]
        :param child: The child of this InlineResponse2001.  # noqa: E501
        :type child: str
        """
        self.openapi_types = {
            '_from': datetime,
            'to': datetime,
            'sku': List[str],
            'child': str
        }

        self.attribute_map = {
            '_from': 'from',
            'to': 'to',
            'sku': 'sku',
            'child': 'child'
        }

        self.__from = _from
        self._to = to
        self._sku = sku
        self._child = child

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _from(self):
        """Gets the _from of this InlineResponse2001.


        :return: The _from of this InlineResponse2001.
        :rtype: datetime
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this InlineResponse2001.


        :param _from: The _from of this InlineResponse2001.
        :type _from: datetime
        """

        self.__from = _from

    @property
    def to(self):
        """Gets the to of this InlineResponse2001.


        :return: The to of this InlineResponse2001.
        :rtype: datetime
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this InlineResponse2001.


        :param to: The to of this InlineResponse2001.
        :type to: datetime
        """

        self._to = to

    @property
    def sku(self):
        """Gets the sku of this InlineResponse2001.


        :return: The sku of this InlineResponse2001.
        :rtype: List[str]
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """Sets the sku of this InlineResponse2001.


        :param sku: The sku of this InlineResponse2001.
        :type sku: List[str]
        """

        self._sku = sku

    @property
    def child(self):
        """Gets the child of this InlineResponse2001.


        :return: The child of this InlineResponse2001.
        :rtype: str
        """
        return self._child

    @child.setter
    def child(self, child):
        """Sets the child of this InlineResponse2001.


        :param child: The child of this InlineResponse2001.
        :type child: str
        """

        self._child = child
