# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InvitationCreateBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, invitee=None, reference_id=None):  # noqa: E501
        """InvitationCreateBody - a model defined in OpenAPI

        :param invitee: The invitee of this InvitationCreateBody.  # noqa: E501
        :type invitee: str
        :param reference_id: The reference_id of this InvitationCreateBody.  # noqa: E501
        :type reference_id: str
        """
        self.openapi_types = {
            'invitee': str,
            'reference_id': str
        }

        self.attribute_map = {
            'invitee': 'invitee',
            'reference_id': 'reference_id'
        }

        self._invitee = invitee
        self._reference_id = reference_id

    @classmethod
    def from_dict(cls, dikt) -> 'InvitationCreateBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The invitation_create_body of this InvitationCreateBody.  # noqa: E501
        :rtype: InvitationCreateBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invitee(self):
        """Gets the invitee of this InvitationCreateBody.


        :return: The invitee of this InvitationCreateBody.
        :rtype: str
        """
        return self._invitee

    @invitee.setter
    def invitee(self, invitee):
        """Sets the invitee of this InvitationCreateBody.


        :param invitee: The invitee of this InvitationCreateBody.
        :type invitee: str
        """

        self._invitee = invitee

    @property
    def reference_id(self):
        """Gets the reference_id of this InvitationCreateBody.


        :return: The reference_id of this InvitationCreateBody.
        :rtype: str
        """
        return self._reference_id

    @reference_id.setter
    def reference_id(self, reference_id):
        """Sets the reference_id of this InvitationCreateBody.


        :param reference_id: The reference_id of this InvitationCreateBody.
        :type reference_id: str
        """

        self._reference_id = reference_id
