# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.invitation_information_body_message_attributes_inner import InvitationInformationBodyMessageAttributesInner
from openapi_server import util

from openapi_server.models.invitation_information_body_message_attributes_inner import InvitationInformationBodyMessageAttributesInner  # noqa: E501

class InvitationCreateBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, expire_time=None, invite_at_time=None, invitee=None, message_attributes=None, reference_id=None, tenant_id=None):  # noqa: E501
        """InvitationCreateBody - a model defined in OpenAPI

        :param expire_time: The expire_time of this InvitationCreateBody.  # noqa: E501
        :type expire_time: datetime
        :param invite_at_time: The invite_at_time of this InvitationCreateBody.  # noqa: E501
        :type invite_at_time: datetime
        :param invitee: The invitee of this InvitationCreateBody.  # noqa: E501
        :type invitee: str
        :param message_attributes: The message_attributes of this InvitationCreateBody.  # noqa: E501
        :type message_attributes: List[InvitationInformationBodyMessageAttributesInner]
        :param reference_id: The reference_id of this InvitationCreateBody.  # noqa: E501
        :type reference_id: str
        :param tenant_id: The tenant_id of this InvitationCreateBody.  # noqa: E501
        :type tenant_id: str
        """
        self.openapi_types = {
            'expire_time': datetime,
            'invite_at_time': datetime,
            'invitee': str,
            'message_attributes': List[InvitationInformationBodyMessageAttributesInner],
            'reference_id': str,
            'tenant_id': str
        }

        self.attribute_map = {
            'expire_time': 'expire_time',
            'invite_at_time': 'invite_at_time',
            'invitee': 'invitee',
            'message_attributes': 'message_attributes',
            'reference_id': 'reference_id',
            'tenant_id': 'tenant_id'
        }

        self._expire_time = expire_time
        self._invite_at_time = invite_at_time
        self._invitee = invitee
        self._message_attributes = message_attributes
        self._reference_id = reference_id
        self._tenant_id = tenant_id

    @classmethod
    def from_dict(cls, dikt) -> 'InvitationCreateBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The invitation_create_body of this InvitationCreateBody.  # noqa: E501
        :rtype: InvitationCreateBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def expire_time(self):
        """Gets the expire_time of this InvitationCreateBody.


        :return: The expire_time of this InvitationCreateBody.
        :rtype: datetime
        """
        return self._expire_time

    @expire_time.setter
    def expire_time(self, expire_time):
        """Sets the expire_time of this InvitationCreateBody.


        :param expire_time: The expire_time of this InvitationCreateBody.
        :type expire_time: datetime
        """

        self._expire_time = expire_time

    @property
    def invite_at_time(self):
        """Gets the invite_at_time of this InvitationCreateBody.


        :return: The invite_at_time of this InvitationCreateBody.
        :rtype: datetime
        """
        return self._invite_at_time

    @invite_at_time.setter
    def invite_at_time(self, invite_at_time):
        """Sets the invite_at_time of this InvitationCreateBody.


        :param invite_at_time: The invite_at_time of this InvitationCreateBody.
        :type invite_at_time: datetime
        """

        self._invite_at_time = invite_at_time

    @property
    def invitee(self):
        """Gets the invitee of this InvitationCreateBody.


        :return: The invitee of this InvitationCreateBody.
        :rtype: str
        """
        return self._invitee

    @invitee.setter
    def invitee(self, invitee):
        """Sets the invitee of this InvitationCreateBody.


        :param invitee: The invitee of this InvitationCreateBody.
        :type invitee: str
        """

        self._invitee = invitee

    @property
    def message_attributes(self):
        """Gets the message_attributes of this InvitationCreateBody.


        :return: The message_attributes of this InvitationCreateBody.
        :rtype: List[InvitationInformationBodyMessageAttributesInner]
        """
        return self._message_attributes

    @message_attributes.setter
    def message_attributes(self, message_attributes):
        """Sets the message_attributes of this InvitationCreateBody.


        :param message_attributes: The message_attributes of this InvitationCreateBody.
        :type message_attributes: List[InvitationInformationBodyMessageAttributesInner]
        """

        self._message_attributes = message_attributes

    @property
    def reference_id(self):
        """Gets the reference_id of this InvitationCreateBody.


        :return: The reference_id of this InvitationCreateBody.
        :rtype: str
        """
        return self._reference_id

    @reference_id.setter
    def reference_id(self, reference_id):
        """Sets the reference_id of this InvitationCreateBody.


        :param reference_id: The reference_id of this InvitationCreateBody.
        :type reference_id: str
        """

        self._reference_id = reference_id

    @property
    def tenant_id(self):
        """Gets the tenant_id of this InvitationCreateBody.


        :return: The tenant_id of this InvitationCreateBody.
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this InvitationCreateBody.


        :param tenant_id: The tenant_id of this InvitationCreateBody.
        :type tenant_id: str
        """

        self._tenant_id = tenant_id
